version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: samrs_db
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: samrs_db
    ports:
      - "5432:5432" 
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Skema DB otomatis jalan

  pgadmin:
    image: dpage/pgadmin4
    container_name: samrs_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80" # Akses di browser: http://localhost:8081
    depends_on:
      - db